INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (1, '트림', '트림(trim)이란, 자동차 한 모델 안에서의 등급을 말해요. 자동차 트림에 따라 선택할 수 있는 편의사양과 옵션등이 정해져요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (2, '클러스터', '클러스터란, 자동차에 적용된 편의, 안전 시스템의 상태 정보를 확인할 수 있는 장치로, 주행 관련 정보를 상황에 맞게 제공해줘요.', 'car_dict/1.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (3, '스티어링 휠', '운전대 또는 핸들을 말해요.', 'car_dict/2.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (4, '파워트레인', '엔진에서 구동바퀴사이의 모든 기관을 지칭하는 말이에요. 자동차 플랫폼과 비슷한 뜻이에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (5, '머플러', '엔진에서 발생한 배기가스를 차 밖으로 배출하는 장치에요. ', 'car_dict/3.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (6, '토크', '자동차의 동력이 엔진 축에 순간적으로 전달되는 힘이에요. 가속 성능, 연비, 엔진 효율에 영향을 줘요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (7, '와류현상', '자동차가 달릴 때, 공기가 흘러 차량 뒤쪽으로 몰리게 되는데, 이때 모이게 된 공기들은 소용돌이를 만들어서 낙엽 등을 머물게 해요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (8, '연비', '연비는 자동차가 1L의 연료로 얼마나 멀리 주행할 수 있는지를 나타낸 수치에요. 연비가 높을수록 적은 기름으로 오래 달릴 수 있어요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (9, '대향차', '외길에서, 반대 방향에서 달려오는 차를 말해요. 너무 위험하겠죠?', 'car_dict/4.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (10, '윈드실드', '흔히 프런트 글라스 또는 앞창이라고 불러요. 공기 저항을 적게 하기 위해서 최근에는 경사가 아주 완만해졌어요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (11, 'AVN', '오디오, 비디오, 내비게이션의 약자에요. 요즘에는 다양한 도메인과 기기들이 연결되면서 보다 더 많은 영역을 담당하고있어요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (12, '조향', '자동차의 진행 방향을 운전자 임의대로 바꾸기 위한 장치에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (13, '랙기어', '운전대 또는 핸들이라고 불리는 스티어링 휠의 회전운동을 직선운동으로 바꿔주는 기어를 뜻해요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (14, '어드밴스드', '4세대 에어백으로, 센서를 이용해 승객의 위치와 체격, 앉은 자세 및 중돌 정도를 판단하여 스스로 팽창 여부를 결정하는 똑똑한 에어백이에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (15, '센터사이드', '운전석과 조수석 사이에 작동하는 에어백으로, 사람과 사람이 서로 부딪히면서 발생할 수 있는 부상을 막아줘요.', 'car_dict/5.gif');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (16, '전복 대응 커튼', '자동차 전복 시 탑승자를 충격으로부터 보호하는 에어백이에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (17, '언더스티어', '커브길에서 핸들을 돌린만큼 차가 돌지 않고 코너 바깥으로 밀려나는 현상이에요. 너무 위험하겠죠?', 'car_dict/6.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (18, '차일드락', '자동차 뒷자석에 탄 어린이의 안전을 위해 차량 도어를 잠글 수 있는 장치에요.', 'car_dict/7.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (19, 'ISO 규격', '자동차 기능 안전성 국제 표준으로, 자동차 기능 안전 국제 규격이에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (20, '등화장치', '운전자의 시야와 정보 전달에 이용되고, 승객을 편리하게 해주며, 다른 운전자에게 신호와 경고 표시를 해주는 장치에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (21, '토크벡터링', '자동차가 사용자가 의도한 대로 움직이도록 이쪽 바퀴는 힘을 더 주고, 저쪽 바퀴는 힘을 덜 주는 기능이에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (22, '글로브 박스', '조수석 앞쪽에 마련된 수납공간이에요.', 'car_dict/8.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (23, '공력성능', '자동차가 공기의 저항을 받는 정도로, 동력성능과 연료 소비효율, 주행 안정성과 소음에 영향을 줘요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (24, '벤트', '공기를 배출하거나 유입하는 구멍으로, 자동차 내부의 통기성을 제공해요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (25, '센터페시아', '대시보드에서 운전석과 조수석 사이의 앞부분에 위치하여, 오디오와 에어컨 등의 기능을 조작하는 각종 버튼을 컨트롤하는 부분이에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (26, '테일게이트', '트렁크 공간을 가리는 문이에요.', 'car_dict/9.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (27, '구동 방식', '엔진에서 발생하는 동력이 바퀴에 전달되어 자동차가 움직이는 방식을 말해요. 동력은 전달받은 바퀴 개수에 따라 2WD와 4WD로 나뉘어요.', 'car_dict/10.png');
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (28, '단조 소재', '금속이 고압 하에서 고 강도 부품으로 소성변형(재료의 탄성한계를 넘어섰을 때 영구적인 변형의 부분)을 하여 성형되는 제조공법이에요.', null);
INSERT INTO ohmycarset.car_dict (id, keyword, description, img_src) VALUES (29, '전동식 틸트 & 스티어링 휠', '운전자에게 적합하도록 운전대 또는 핸들이라고 불리는 스티어링 휠의 위치를 조정할 수 있는 기능이에요.', null);
