INSERT INTO default_option values (1, '8단 자동변속기', 'default_option/1_1.png', 1);
INSERT INTO default_option values (2, 'ISG 시스템', 'default_option/1_2.png', 1);
INSERT INTO default_option values (3, '통합주행모드', 'default_option/1_3.png', 1);
INSERT INTO default_option values (4, '랙구동형 전동식 파워 스티어링(R-MDPS)', 'default_option/1_4.png', 1);
INSERT INTO default_option values (5, '전자식 변속버튼', 'default_option/1_5.png',1);
INSERT INTO default_option values (6, '하이빔 보조', 'default_option/2_1.png', 2);
INSERT INTO default_option values (7, '진동 경고 스티어링 휠', 'default_option/2_2.png', 2);
INSERT INTO default_option values (8, '스마트 크루즈 컨트롤(스탑앤고 기능 포함)', 'default_option/2_3.png', 2);
INSERT INTO default_option values (9, '내비게이션 기반 스마트 크루즈 컨트롤(안전구간, 곡선로)', 'default_option/2_4.png', 2);
INSERT INTO default_option values (10, '고속도로 주행 보조', 'default_option/2_5.png', 2);
INSERT INTO default_option values (11, '차로 유지 보조', 'default_option/2_6.png', 2);
INSERT INTO default_option values (12, '전방 충돌방지 보조(차량/보행자/자전거 탑승자/교차로 대향차)', 'default_option/2_7.png', 2);
INSERT INTO default_option values (13, '차로 이탈방지 보조', 'default_option/2_8.png', 2);
INSERT INTO default_option values (14, '운전자 주의 경고', 'default_option/2_9.png', 2);
INSERT INTO default_option values (15, '후측방 충돌 경고(주행)', 'default_option/2_10.png', 2);
INSERT INTO default_option values (16, '후측방 충돌방지 보조(전진 출차)', 'default_option/2_11.png', 2);
INSERT INTO default_option values (17, '안전 하차 보조', 'default_option/2_12.png', 2);
INSERT INTO default_option values (18, '후방 교차 충돌방지 보조', 'default_option/2_13.png', 2);
INSERT INTO default_option values (19, '전방 충돌방지 보조(교차 차량/추월시 대향차/측방 접근차)', 'default_option/2_14.png', 2);
INSERT INTO default_option values (20, '내비게이션 기반 스마트 크루즈 컨트롤(진출입로)', 'default_option/2_15.png', 2);
INSERT INTO default_option values (21, '고속도로 주행 보조 2', 'default_option/2_16.png', 2);
INSERT INTO default_option values (22, '후방 주차 충돌방지 보조', 'default_option/2_17.png', 2);
INSERT INTO default_option values (23, '원격 스마트 주차 보조', 'default_option/2_18.png', 2);
INSERT INTO default_option values (24, '후석 승객 알림', 'default_option/2_19.png', 2);
INSERT INTO default_option values (25, '10에어백 시스템(1열 어드밴스드/센터사이드, 1/2열 사이드, 운전석 무릎, 전복대응 커튼', 'default_option/3_1.png', 3);
INSERT INTO default_option values (26, '유아용 시트 고정장치(2열 2개/3열 1개)', 'default_option/3_2.png', 3);
INSERT INTO default_option values (27, '구동선회 제어기능', 'default_option/3_3.png', 3);
INSERT INTO default_option values (28, '다중 충돌방지 자동 제동 시스템', 'default_option/3_4.png', 3);
INSERT INTO default_option values (29, '다크 크롬 라디에이터 그릴', 'default_option/4_1.png', 4);
INSERT INTO default_option values (30, 'LED 주간주행등', 'default_option/4_2.png', 4);
INSERT INTO default_option values (31, 'LED 포지셔닝램프', 'default_option/4_3.png', 4);
INSERT INTO default_option values (32, 'LED 방향지시등', 'default_option/4_4.png', 4);
INSERT INTO default_option values (33, 'Full LED 헤드램프(프로젝션 타입)', 'default_option/4_5.png', 4);
INSERT INTO default_option values (34, '아웃사이드 미러(열선, 전동접이, 전동조절, LED 방향지시등', 'default_option/4_6.png', 4);
INSERT INTO default_option values (35, '이중접합 차음유리(윈드실드, 1/2열 도어)', 'default_option/4_7.png', 4);
INSERT INTO default_option values (36, '도어 포켓 라이팅(1열)', 'default_option/4_8.png', 4);
INSERT INTO default_option values (37, '싱글 트윈팁 머플러', 'default_option/4_9.png', 4);
INSERT INTO default_option values (38, '18인치 알로이 휠 & 타이어', 'default_option/4_10.png', 4);
INSERT INTO default_option values (39, 'LED 리어콤비램프', 'default_option/4_11.png', 4);
INSERT INTO default_option values (40, 'LED 보조제동등', 'default_option/4_12.png', 4);
INSERT INTO default_option values (41, '후진가이드램프', 'default_option/4_13.png', 4);
INSERT INTO default_option values (42, '리어 스포일러', 'default_option/4_14.png', 4);
INSERT INTO default_option values (43, '크롬 DLO 몰딩', 'default_option/4_15.png', 4);
INSERT INTO default_option values (44, '루프랙', 'default_option/4_16.png', 4);
INSERT INTO default_option values (45, '메탈페인트 스키드 플레이트', 'default_option/4_17.png', 4);
INSERT INTO default_option values (46, '20인치 알로이 휠 & 타이어', 'default_option/4_18.png', 4);
INSERT INTO default_option values (47, '발수 도어(1열)', 'default_option/4_19.png', 4);
INSERT INTO default_option values (48, '퍼들램프', 'default_option/4_20.png', 4);
INSERT INTO default_option values (49, '캘리그래피 전용 디자인(휠, 라디에이터 그릴 & 가니쉬, 인테이크 그릴, 바디컬러 클래딩, 프론트 & 리어 크롬 스키드 플레이트)', 'default_option/4_21.png', 4);
INSERT INTO default_option values (50, '클러스터(4.2인치 컬러 LCD)', 'default_option/5_1.png', 5);
INSERT INTO default_option values (51, '베젤리스 인사이드 미러', 'default_option/5_2.png', 5);
INSERT INTO default_option values (52, 'LED 실내등(맵램프, 룸램프, 선바이저램프, 러기지램프)', 'default_option/5_3.png', 5);
INSERT INTO default_option values (53, '가죽 스티어링 휠(열선포함)', 'default_option/5_4.png', 5);
INSERT INTO default_option values (54, '클러스터(12.3인치 컬러 LCD)', 'default_option/5_5.png', 5);
INSERT INTO default_option values (55, '인조가죽 감싸기', 'default_option/5_6.png', 5);
INSERT INTO default_option values (56, '도어 암레스트 리얼스티치', 'default_option/5_7.png', 5);
INSERT INTO default_option values (57, '메탈 페달', 'default_option/5_8.png', 5);
INSERT INTO default_option values (58, '스웨이드 내장재(헤드라이닝/필라)', 'default_option/5_9.png', 5);
INSERT INTO default_option values (59, '콘솔 커버 리얼 알루미늄', 'default_option/5_10.png', 5);
INSERT INTO default_option values (60, '메탈 리어범퍼스텝', 'default_option/5_11.png', 5);
INSERT INTO default_option values (61, '메탈 도어스커프', 'default_option/5_12.png', 5);
INSERT INTO default_option values (62, '1열 도어 스피커 메탈 그릴', 'default_option/5_13.png', 5);
INSERT INTO default_option values (63, '퀼팅 인조가죽 감싸기(도어트림)', 'default_option/5_14.png', 5);
INSERT INTO default_option values (64, '앰비언트 무드램프', 'default_option/5_15.png', 5);
INSERT INTO default_option values (65, '디지털 센터 미러', 'default_option/5_16.png', 5);
INSERT INTO default_option values (66, '콘솔 사이드 리얼스티치', 'default_option/5_17.png', 5);
INSERT INTO default_option values (67, '운전석 전동시트(8way, 럼버서포트)', 'default_option/6_1.png', 6);
INSERT INTO default_option values (68, '1열 열선/통풍시트', 'default_option/6_2.png', 6);
INSERT INTO default_option values (69, '2열 열선시트', 'default_option/6_3.png', 6);
INSERT INTO default_option values (70, '2열 통풍시트', 'default_option/6_4.png', 6);
INSERT INTO default_option values (71, '2열 폴드 & 다이브/슬라이딩 & 리클라이닝 시트', 'default_option/6_5.png', 6);
INSERT INTO default_option values (72, '3열 6:4분할 폴딩/리클라이닝 시트', 'default_option/6_6.png', 6);
INSERT INTO default_option values (73, '3열 파워폴딩시트', 'default_option/6_7.png', 6);
INSERT INTO default_option values (74, '3열 열선시트', 'default_option/6_8.png', 6);
INSERT INTO default_option values (75, '7인승 시트', 'default_option/6_9.png', 6);
INSERT INTO default_option values (76, '운전석 전동시트(10way, 4way 럼버서포트, 쿠션 익스텐션, 자세 메모리 시스템)', 'default_option/6_10.png', 6);
INSERT INTO default_option values (77, '운전석 에르고 모션 시트(18way, 볼스터 전동조절, 레그레스트, 릴렉션 컴포트, 스트레칭 모드)', 'default_option/6_11.png', 6);
INSERT INTO default_option values (78, '동승석 전동시트(8way, 워크인 디바이스)', 'default_option/6_12.png', 6);
INSERT INTO default_option values (79, '동승석 전동시트(럼버서포트, 레그레스트, 릴렉션 컴포트)', 'default_option/6_13.png', 6);
INSERT INTO default_option values (80, '인조가죽 시트(블랙)', 'default_option/6_14.png', 6);
INSERT INTO default_option values (81, '퀼팅 나파가죽 시트(블랙/버건디/웜그레이)', 'default_option/6_15.png', 6);
INSERT INTO default_option values (82, '캘리그래피 전용 퀼팅 나파가죽 시트(블랙/브라운/웜그레이)', 'default_option/6_16.png', 6);
INSERT INTO default_option values (83, '스마트 자세제어', 'default_option/6_17.png', 6);
INSERT INTO default_option values (84, '윙타입 헤드레스트(2열)', 'default_option/6_18.png', 6);
INSERT INTO default_option values (85, '퀼팅 천연가죽 시트(블랙/쿨그레이)', 'default_option/6_19.png', 6);
INSERT INTO default_option values (86, '버튼시동 & 스마트키','default_option/7_1.png' , 7);
INSERT INTO default_option values (87, '전동식 파킹 브레이크(오토홀드 포함)','default_option/7_2.png' , 7);
INSERT INTO default_option values (88, '패들 쉬프트','default_option/7_3.png' , 7);
INSERT INTO default_option values (89, '수동식 틸트 & 텔레스코픽 스티어링 휠','default_option/7_4.png' , 7);
INSERT INTO default_option values (90, '3존 독립제어 풀오토 에어컨(공기청정모드 포함)','default_option/7_5.png' , 7);
INSERT INTO default_option values (91, '공기질 센서','default_option/7_6.png' , 7);
INSERT INTO default_option values (92, '마이크로 에어 필터','default_option/7_7.png' , 7);
INSERT INTO default_option values (93, '자외선 차단 유리(윈드실드)','default_option/7_8.png' , 7);
INSERT INTO default_option values (94, '오토 디포그','default_option/7_9.png' , 7);
INSERT INTO default_option values (95, '레인센서','default_option/7_10.png' , 7);
INSERT INTO default_option values (96, '운전석 공조 연동 자동 제어','default_option/7_11.png' , 7);
INSERT INTO default_option values (97, 'USB 충전기(1열 1개, 2열 2개, 3열 2개)','default_option/7_12.png' , 7);
INSERT INTO default_option values (98, '파워 아웃렛(1열 1개, 2열 1개, 3열 1개)','default_option/7_13.png' , 7);
INSERT INTO default_option values (99, '세이프티 파워 윈도우(1/2열)','default_option/7_14.png' , 7);
INSERT INTO default_option values (100, '후방 모니터','default_option/7_15.png' , 7);
INSERT INTO default_option values (101, '확산형 루프 에어 벤트','default_option/7_16.png' , 7);
INSERT INTO default_option values (102, '오토라이트 컨트롤','default_option/7_17.png' , 7);
INSERT INTO default_option values (103, '스마트키 원격시동','default_option/7_18.png' , 7);
INSERT INTO default_option values (104, '전방/후방 주차 거리 경고','default_option/7_19.png' , 7);
INSERT INTO default_option values (105, '전동식 틸트 & 텔레스코픽 스티어링 휠','default_option/7_20.png' , 7);
INSERT INTO default_option values (106, '스마트폰 무선충전','default_option/7_21.png' , 7);
INSERT INTO default_option values (107, '스마트 파워 테일게이트','default_option/7_22.png' , 7);
INSERT INTO default_option values (108, '서라운드 뷰 모니터','default_option/7_23.png' , 7);
INSERT INTO default_option values (109, '후측방 모니터','default_option/7_24.png' , 7);
INSERT INTO default_option values (110, '디지털 키 2 터치','default_option/7_25.png' , 7);
INSERT INTO default_option values (111, '2열 수동식 도어커튼','default_option/7_26.png' , 7);
INSERT INTO default_option values (112, '전후석 통합 터치 공조 컨트롤','default_option/7_27.png' , 7);
INSERT INTO default_option values (113, '헤드업 디스플레이','default_option/7_28.png' , 7);
INSERT INTO default_option values (114, '파워 아웃렛(콘솔 내부 1개)','default_option/7_29.png' , 7);
INSERT INTO default_option values (115, 'USB 충전기(콘솔 내부 1개)','default_option/7_30.png' , 7);
INSERT INTO default_option values (116, '12.3인치 내비게이션(블루링크, 폰 프로젝션, 현대 카페이)','default_option/8_1.png' , 8);
INSERT INTO default_option values (117, '하이패스','default_option/8_2.png' , 8);
INSERT INTO default_option values (118, '후석 대화모드','default_option/8_3.png' , 8);
INSERT INTO default_option values (119, '후석 취침모드','default_option/8_4.png' , 8);
INSERT INTO default_option values (120, '멀티미디어용 USB 단자(1열 1개)','default_option/8_5.png' , 8);
INSERT INTO default_option values (121, '일반 오디오 시스템(8스피커, 블루투스 핸즈프리)','default_option/8_6.png' , 8);
INSERT INTO default_option values (122, 'KRELL 프리미엄 사운드(12스피커, 외장앰프)','default_option/8_7.png', 8);
INSERT INTO default_option values (123, '액티브 노이즈 컨트롤','default_option/8_8.png', 8);

