INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (1, '인조가죽(블랙)', 'interior_color/1.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (2, '퀼팅 천연(블랙)', 'interior_color/2.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (3, '쿨그레이', 'interior_color/3.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (4, '블랙', 'interior_color/4.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (5, '웜그레이', 'interior_color/5.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (6, '버건디', 'interior_color/6.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (7, '블랙 고급', 'interior_color/7.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (8, '블랙 원톤', 'interior_color/8.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (9, '브라운', 'interior_color/9.png');
INSERT INTO ohmycarset.interior_color (id, name, img_src) VALUES (10, '네이비/웜그레이 투톤', 'interior_color/10.png');
